name: add_to_numbers
description: add_to_numbers is a Dart library designed as a starting point for building Dart libraries or applications. With version 1.0.0, this package provides a foundational structure that you can build upon for your own Dart projects. It comes with essential development dependencies such as lints for code quality checks and test for unit testing. The package is compatible with Dart SDK version ^3.4.4 and is licensed under the MIT License. For more information and to access the source code, visit the GitHub repository.
version: 1.0.0
repository: https://github.com/Tursunali008/add_to_numbers

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# License information
# See LICENSE file for the full license text
license: MIT